export const directions = [
  {
    id: "01",
    name: "Studio",
    mood: "Blush canvas · oversized type · split composition",
    color: "#efd8d1",
    title: ["Your skin.", "Your rules."],
  },
  {
    id: "02",
    name: "Campaign",
    mood: "Immersive photography · cinematic scale · minimal framing",
    color: "#273e42",
    title: ["Entirely,", "uniquely you."],
  },
  {
    id: "03",
    name: "Skin Lab",
    mood: "Mint · product first · clear, functional hierarchy",
    color: "#dcebdd",
    title: ["Know more.", "Guess less."],
  },
  {
    id: "04",
    name: "The Edit",
    mood: "Magazine columns · sharp rules · considered typography",
    color: "#f0eee9",
    title: ["The skin", "you're in."],
  },
  {
    id: "05",
    name: "Soft Form",
    mood: "Lavender · sculptural portrait · centred story",
    color: "#e3dcef",
    title: ["A little closer", "to yourself."],
  },
  {
    id: "06",
    name: "After Hours",
    mood: "Burgundy · monumental serif · intimate portrait",
    color: "#45252c",
    title: ["Beauty,", "on your terms."],
  },
  {
    id: "07",
    name: "Daylight",
    mood: "Butter yellow · image first · effortless editorial",
    color: "#f3edc9",
    title: ["Meet your", "everyday glow."],
  },
  {
    id: "08",
    name: "Neue",
    mood: "Electric blue · modular grid · bold graphic energy",
    color: "#dbe5fa",
    title: ["SKIN.", "DECODED."],
  },
  {
    id: "09",
    name: "The Gallery",
    mood: "White space · photographic diptych · gallery typography",
    color: "#f7f7f2",
    title: ["Nothing generic.", "Only personal."],
  },
  {
    id: "10",
    name: "Ritual Club",
    mood: "Terracotta · rounded blocks · approachable confidence",
    color: "#ecc7b2",
    title: ["Less scrolling.", "More caring."],
  },
  {
    id: "11",
    name: "Precision",
    mood: "Monochrome · typographic system · interface at the centre",
    color: "#e9eae5",
    title: ["A clearer read.", "A smarter ritual."],
  },
  {
    id: "12",
    name: "Signature",
    mood: "Oversized masthead · oxblood + blush · beauty meets technology",
    color: "#eed9d2",
    title: ["Skin.", "Understood."],
  },
] as const;
export type Direction = (typeof directions)[number];
